//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Ada.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAdaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class AdaBaseListener : IAdaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] AdaParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] AdaParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.procedureDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureDeclaration([NotNull] AdaParser.ProcedureDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.procedureDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureDeclaration([NotNull] AdaParser.ProcedureDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameters([NotNull] AdaParser.FormalParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameters([NotNull] AdaParser.FormalParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] AdaParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] AdaParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] AdaParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] AdaParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.parameterMode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterMode([NotNull] AdaParser.ParameterModeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.parameterMode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterMode([NotNull] AdaParser.ParameterModeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierList([NotNull] AdaParser.IdentifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierList([NotNull] AdaParser.IdentifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.declarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarations([NotNull] AdaParser.DeclarationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.declarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarations([NotNull] AdaParser.DeclarationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] AdaParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] AdaParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] AdaParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] AdaParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclaration([NotNull] AdaParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclaration([NotNull] AdaParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.typeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDefinition([NotNull] AdaParser.TypeDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.typeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDefinition([NotNull] AdaParser.TypeDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.indexRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexRange([NotNull] AdaParser.IndexRangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.indexRange"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexRange([NotNull] AdaParser.IndexRangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] AdaParser.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] AdaParser.TypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatements([NotNull] AdaParser.StatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatements([NotNull] AdaParser.StatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] AdaParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] AdaParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.assignmentStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentStatement([NotNull] AdaParser.AssignmentStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.assignmentStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentStatement([NotNull] AdaParser.AssignmentStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] AdaParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] AdaParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.arrayAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccess([NotNull] AdaParser.ArrayAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.arrayAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccess([NotNull] AdaParser.ArrayAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] AdaParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] AdaParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.loopStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopStatement([NotNull] AdaParser.LoopStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.loopStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopStatement([NotNull] AdaParser.LoopStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] AdaParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] AdaParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.procedureCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureCall([NotNull] AdaParser.ProcedureCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.procedureCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureCall([NotNull] AdaParser.ProcedureCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.actualParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActualParameters([NotNull] AdaParser.ActualParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.actualParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActualParameters([NotNull] AdaParser.ActualParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] AdaParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] AdaParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] AdaParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] AdaParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.exitStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExitStatement([NotNull] AdaParser.ExitStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.exitStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExitStatement([NotNull] AdaParser.ExitStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] AdaParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] AdaParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.relationalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalOperator([NotNull] AdaParser.RelationalOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.relationalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalOperator([NotNull] AdaParser.RelationalOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.simpleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleExpression([NotNull] AdaParser.SimpleExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.simpleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleExpression([NotNull] AdaParser.SimpleExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.sign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSign([NotNull] AdaParser.SignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.sign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSign([NotNull] AdaParser.SignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.addingOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddingOperator([NotNull] AdaParser.AddingOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.addingOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddingOperator([NotNull] AdaParser.AddingOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] AdaParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] AdaParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.multiplyingOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplyingOperator([NotNull] AdaParser.MultiplyingOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.multiplyingOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplyingOperator([NotNull] AdaParser.MultiplyingOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] AdaParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] AdaParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] AdaParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] AdaParser.PrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] AdaParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] AdaParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerLiteral([NotNull] AdaParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerLiteral([NotNull] AdaParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.realLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRealLiteral([NotNull] AdaParser.RealLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.realLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRealLiteral([NotNull] AdaParser.RealLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.stringLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLiteral([NotNull] AdaParser.StringLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.stringLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLiteral([NotNull] AdaParser.StringLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] AdaParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] AdaParser.IdentifierContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
