//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Ada.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="AdaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IAdaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] AdaParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] AdaParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.procedureDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureDeclaration([NotNull] AdaParser.ProcedureDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.procedureDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureDeclaration([NotNull] AdaParser.ProcedureDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameters([NotNull] AdaParser.FormalParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameters([NotNull] AdaParser.FormalParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] AdaParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] AdaParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] AdaParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] AdaParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.parameterMode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterMode([NotNull] AdaParser.ParameterModeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.parameterMode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterMode([NotNull] AdaParser.ParameterModeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierList([NotNull] AdaParser.IdentifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierList([NotNull] AdaParser.IdentifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarations([NotNull] AdaParser.DeclarationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarations([NotNull] AdaParser.DeclarationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] AdaParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] AdaParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] AdaParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] AdaParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclaration([NotNull] AdaParser.TypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclaration([NotNull] AdaParser.TypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.typeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDefinition([NotNull] AdaParser.TypeDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.typeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDefinition([NotNull] AdaParser.TypeDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.indexRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexRange([NotNull] AdaParser.IndexRangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.indexRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexRange([NotNull] AdaParser.IndexRangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeName([NotNull] AdaParser.TypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeName([NotNull] AdaParser.TypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatements([NotNull] AdaParser.StatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatements([NotNull] AdaParser.StatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] AdaParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] AdaParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentStatement([NotNull] AdaParser.AssignmentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentStatement([NotNull] AdaParser.AssignmentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] AdaParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] AdaParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayAccess([NotNull] AdaParser.ArrayAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayAccess([NotNull] AdaParser.ArrayAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] AdaParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] AdaParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.loopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopStatement([NotNull] AdaParser.LoopStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.loopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopStatement([NotNull] AdaParser.LoopStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] AdaParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] AdaParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.procedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureCall([NotNull] AdaParser.ProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.procedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureCall([NotNull] AdaParser.ProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.actualParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActualParameters([NotNull] AdaParser.ActualParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.actualParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActualParameters([NotNull] AdaParser.ActualParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] AdaParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] AdaParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] AdaParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] AdaParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] AdaParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] AdaParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalOperator([NotNull] AdaParser.RelationalOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalOperator([NotNull] AdaParser.RelationalOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.simpleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleExpression([NotNull] AdaParser.SimpleExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.simpleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleExpression([NotNull] AdaParser.SimpleExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.sign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSign([NotNull] AdaParser.SignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.sign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSign([NotNull] AdaParser.SignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.addingOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddingOperator([NotNull] AdaParser.AddingOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.addingOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddingOperator([NotNull] AdaParser.AddingOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] AdaParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] AdaParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.multiplyingOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplyingOperator([NotNull] AdaParser.MultiplyingOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.multiplyingOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplyingOperator([NotNull] AdaParser.MultiplyingOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] AdaParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] AdaParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] AdaParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] AdaParser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] AdaParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] AdaParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerLiteral([NotNull] AdaParser.IntegerLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerLiteral([NotNull] AdaParser.IntegerLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.realLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRealLiteral([NotNull] AdaParser.RealLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.realLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRealLiteral([NotNull] AdaParser.RealLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringLiteral([NotNull] AdaParser.StringLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringLiteral([NotNull] AdaParser.StringLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AdaParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] AdaParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AdaParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] AdaParser.IdentifierContext context);
}
