//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Ada.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AdaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IAdaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] AdaParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.procedureDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureDeclaration([NotNull] AdaParser.ProcedureDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormalParameters([NotNull] AdaParser.FormalParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] AdaParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] AdaParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.parameterMode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterMode([NotNull] AdaParser.ParameterModeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierList([NotNull] AdaParser.IdentifierListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarations([NotNull] AdaParser.DeclarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] AdaParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] AdaParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDeclaration([NotNull] AdaParser.TypeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.typeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDefinition([NotNull] AdaParser.TypeDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.indexRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexRange([NotNull] AdaParser.IndexRangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeName([NotNull] AdaParser.TypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatements([NotNull] AdaParser.StatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] AdaParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentStatement([NotNull] AdaParser.AssignmentStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] AdaParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAccess([NotNull] AdaParser.ArrayAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] AdaParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.loopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopStatement([NotNull] AdaParser.LoopStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] AdaParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.procedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureCall([NotNull] AdaParser.ProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.actualParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActualParameters([NotNull] AdaParser.ActualParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] AdaParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] AdaParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] AdaParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalOperator([NotNull] AdaParser.RelationalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.simpleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleExpression([NotNull] AdaParser.SimpleExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.sign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSign([NotNull] AdaParser.SignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.addingOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddingOperator([NotNull] AdaParser.AddingOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] AdaParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.multiplyingOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplyingOperator([NotNull] AdaParser.MultiplyingOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] AdaParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] AdaParser.PrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] AdaParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerLiteral([NotNull] AdaParser.IntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.realLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRealLiteral([NotNull] AdaParser.RealLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteral([NotNull] AdaParser.StringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AdaParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] AdaParser.IdentifierContext context);
}
